In [42]:
import numpy as np

In [43]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [45]:
arr.shape[0] #rows 1   #columns 0 

3

In [29]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr.ndim

2

In [47]:
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [48]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr[1,1]

5

In [49]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [54]:
np.random.randn(2,5,3)

array([[[-0.77989501,  0.1883619 , -0.70647634],
        [-0.08733795, -1.08198987,  0.78504924],
        [ 0.10598562, -0.08156836, -0.57071854],
        [ 0.59012987, -0.57817508,  1.85366444],
        [-0.50725031,  1.44572003, -0.59663508]],

       [[-1.26010589, -0.13370987,  0.32582293],
        [ 1.44907017, -1.92223266, -0.92593367],
        [ 0.57566452,  1.9262976 ,  0.72047645],
        [-0.33993836, -0.0274181 ,  0.83046811],
        [ 0.53520108,  1.44144147,  0.08276997]]])

In [10]:
arr.sum(axis=0)

array([12, 15, 18])

In [11]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a,"\n",b)

[[1 2]
 [3 4]] 
 [[5 6]
 [7 8]]


In [55]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [13]:
a.ravel()

array([1, 2, 3, 4])

In [14]:
np.log(a)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [15]:
a

array([[1, 2],
       [3, 4]])